version: '2'
services:
  node-exporter:
    image: prom/node-exporter:latest
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.global: 'true'
  prom-conf:
    image: infinityworks/prom-conf:19
    network_mode: none
    volumes:
    - ${PROM_VOLUME}:/etc/prom-conf:rw
    tty: true
    links:
    - node-exporter:node-exporter
    - cadvisor:cadvisor
    - prometheus-rancher-exporter:prometheus-rancher-exporter
  graf-db:
    image: infinityworks/graf-db:11
    network_mode: none
    volumes:
    - ${GRAF_VOLUME}:/var/lib/grafana:rw
    tty: true
    links:
    - prometheus:prometheus
    - prometheus-rancher-exporter:prometheus-rancher-exporter
    command:
    - cat
  grafana:
    image: grafana/grafana:4.2.0
    environment:
#      GF_ADMIN_PASSWORD:${GRAF_ADMINPW}
      GF_ALLOW_SIGN_UP: false
    tty: true
    links:
    - prometheus-rancher-exporter:prometheus-rancher-exporter
    - prometheus:prometheus
    volumes_from:
    - graf-db
    ports:
    - 3000:3000/tcp
    labels:
      io.rancher.sidekicks: graf-db
  prometheus-rancher-exporter:
    image: infinityworks/prometheus-rancher-exporter:v0.22.52
    tty: true
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
  cadvisor:
    image: google/cadvisor:v0.28.0
    stdin_open: true
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    tty: true
    labels:
      io.rancher.scheduler.global: 'true'
#  MonitorLB:
#    image: rancher/lb-service-haproxy:v0.7.6
#    ports:
#    - 443:443/tcp
#    - 9090:9090/tcp
#    - 9093:9093/tcp
#    labels:
#      io.rancher.scheduler.affinity:host_label: load_balancer=true
#      io.rancher.container.agent.role: environmentAdmin
#      io.rancher.container.create_agent: 'true'
  prometheus:
    image: prom/prometheus:v2.0.0
    volumes:
    - prometheus-data:/prometheus
    tty: true
    extra_hosts:
    - rancher-server:${RANCHER_IP}
    links:
    - node-exporter:node-exporter
    - cadvisor:cadvisor
    - prometheus-rancher-exporter:prometheus-rancher-exporter
    volumes_from:
    - prom-conf
    ports:
    - 9090:9090/tcp
    command:
    - -alertmanager.url=http://alertmanager:9093
    - -config.file=/etc/prom-conf/prometheus.yml
    - -storage.local.path=/prometheus
    - -web.console.libraries=/etc/prometheus/console_libraries
    - -web.console.templates=/etc/prometheus/consoles
    labels:
      io.rancher.sidekicks: prom-conf
