name: Prometheus Monitoring 2.0
version: v0.1
description: |
  Monitoring Stack with Prometheus v2.0, Grafana, cAdvisor, node-exporter, rancher-exporter, LoadBalancer and predefined dashboards
category: Tools
minimum_rancher_version: v1.6.6
maintainer: Peter Scholta
